### ISSUE TITLE
New sphinx builder from 0.5.0 is compatible with readthedocs extension.

### ISSUE THREAD

**Issue by DriesSchaumont** [DriesSchaumont/sphinx-subprojecttoctree#55]
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/subprojecttoctree-example-subproject/envs/latest/lib/python3.8/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/subprojecttoctree-example-subproject/envs/latest/lib/python3.8/site-packages/sphinx/application.py", line 337, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/subprojecttoctree-example-subproject/envs/latest/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/subprojecttoctree-example-subproject/envs/latest/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 358, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/subprojecttoctree-example-subproject/envs/latest/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 524, in write
    self.prepare_writing(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/subprojecttoctree-example-subproject/envs/latest/lib/python3.8/site-packages/subprojecttoctree/builders.py", line 10, in prepare_writing
    last_master_entry = self.env.last_master_entry
AttributeError: 'BuildEnvironment' object has no attribute 'last_master_entry'
```

**Comment by Iain-S** [comment]
@DriesSchaumont I'm still getting this error, both locally and on readthedocs, using sphinx-subprojecttoctree v5.4 and sphinx v7.2.6. I can't see any reference to `last_master_entry` anywhere in the [Sphinx BuildEnvironment](https://github.com/sphinx-doc/sphinx/blob/2b02173617cbf1c334f8f908f07391c9f09712b5/sphinx/environment/__init__.py) class.

**Comment by Iain-S** [comment]
*Update* I've worked out that this happened because the only item in the master toctree was a reference to the sub-project. You may want to guard against this (admittedly unlikely) scenario.

**Comment by DriesSchaumont** [comment]
Hi @Iain-S, thanks for letting me know! I will create a seperate issue to track this.
